name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 5 * * FRI'

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'fedora',   tag: 'latest'}
          - {dockerfile: 'fedora',   tag: 'rawhide',          build_args: 'TAG=rawhide', continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: 'latest'}
          - {dockerfile: 'ubuntu',   tag: 'rolling',          build_args: 'TAG=rolling'}
          - {dockerfile: 'ubuntu',   tag: 'devel',            build_args: 'TAG=devel', continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: '18.04',            build_args: 'TAG=18.04'}
          - {dockerfile: 'opensuse', tag: 'latest'}
          - {dockerfile: 'fedora',   tag: 'intel',            build_args: 'TAG=34,INTEL=yes'}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2.3.2
      # See https://bugzilla.redhat.com/show_bug.cgi?id=1988199#c3 for more information
      - name: Download Docker with patched seccomp
        run: |
          sudo systemctl stop docker containerd
          sudo apt-get remove --autoremove -y moby-engine moby-cli moby-buildx moby-containerd moby-runc
          sudo add-apt-repository -y ppa:pascallj/docker.io-clone3
          sudo apt-get install -y docker.io
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1.1.0
        with:
          repository: kokkos/ci-containers/${{ matrix.config.dockerfile }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
